### ISSUE TITLE
iOs build failure after version update.

### ISSUE THREAD

**Issue by sandspoof** [PDFTron/pdftron-flutter#101]
Hi, I've updated pdftron_flutter version from 0.0.46 to 0.0.57 and at the building stage I get this error:

_Error output from CocoaPods:
↳
    /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/external_sources/podspec_source.rb:19: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install

Build failed :|
Failed to build for iOS_

I've tried running _pod repo update_, _pod install_ and _pod install --repo-update_ with _flutter clean afterwards_ but this error does not change.

I don't know what to try next.

Configurations:
Flutter: 2.0.3
XCode: 12.5
CocoaPods 1.10.0

Any help would be appreciated!

**Comment by JamesTron** [comment]
Hmm, could you please try de-integrating PDFTron using cocoapod's `deintegrate` command, and then installing it again.

**Comment by sandspoof** [comment]
Hi @JamesTron 

Apologies for the late reply.

Solved it. I was trying anything and updated my flutter version from 2.0.3 to 2.2.2, and Dart version to 2.13.3, ran _pod repo update_ and then I was able to build successfully.

In conclusion, I don't know what exactly was the problem, but maybe it was just my outdated flutter/dart versions

Thank you for the response.

**Comment by JamesTron** [comment]
OK, good to know, thank you for sharing your solution here!
