### ISSUE TITLE
`await controller.openDocument()` is not being waited on

### ISSUE THREAD

**Issue by dcupidon** [PDFTron/pdftron-flutter#107]
**Describe the bug**
Other `DocumentViewController` methods are running before `openDocument()` finishes even though the `await` keyword is being used. When debugging with Android Studio, I realized that `onTabDocumentLoaded` was not being called after `openDocument`.

**Steps to Reproduce the Problem**
1. Use `example/lib/main.dart` and uncomment the code needed to use the widget view.
2. In `onDocumentViewCreated` place any method call after `await controller.openDocument(_document, config: config);`, where `_document` = "https://pdftron.s3.amazonaws.com/downloads/pl/PDFTRON_mobile_about.pdf"
3. Run app

**Expected behavior**
The document would have opened as normal and the methods called would have ran in order.

**Screenshots**
Call stack: 
<img width="571" alt="Screen Shot 2021-07-09 at 12 29 16 PM" src="https://user-images.githubusercontent.com/83605527/125127482-6f88c680-e0b1-11eb-9edc-fb5bf834f44e.png">

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android
 - Device: Pixel 3a
 - OS: Android 11

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel, please report issues through our official channel at https://apryse.com/support
