### ISSUE TITLE
Will it support .xls files?

### ISSUE THREAD

**Issue by xSILENCEx** [PDFTron/pdftron-flutter#12]
When I try to open the .xls file the following error is printed:

E/@@@@@@@@@@@@@@(26094): shadow collectcollect：AppEvent
E/@@@@@@@@@@@@@@(26094): fff phone (IBinder)checkService_Method.invoke(null, name):null
E/Shadow  (26094): Can't find shadow_server
E/@@@@@@@@@@@@@@(26094): shadow mInitialized：false
I/FloatingActionButton(26094): Setting a custom background is not supported.
I/chatty  (26094): uid=10109(com.liugl.fluttermedia) identical 2 lines
I/FloatingActionButton(26094): Setting a custom background is not supported.
I/Choreographer(26094): Skipped 12 frames!  The application may be doing too much work on its main thread.
E/@@@@@@@@@@@@@@(26094): shadow collectcollect：AppEvent
E/@@@@@@@@@@@@@@(26094): fff phone (IBinder)checkService_Method.invoke(null, name):null
E/Shadow  (26094): Can't find shadow_server
E/@@@@@@@@@@@@@@(26094): shadow mInitialized：false
E/WindowManager(26094):
E/WindowManager(26094): android.view.WindowLeaked: Activity com.pdftron.pdf.controls.DocumentActivity has leaked window DecorView@b2138a4[] that was originally added here
E/WindowManager(26094): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:506)
E/WindowManager(26094): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:349)
E/WindowManager(26094): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
E/WindowManager(26094): 	at android.app.Dialog.show(Dialog.java:345)
E/WindowManager(26094): 	at com.pdftron.pdf.utils.Utils.safeShowAlertDialog(Utils.java:1850)
E/WindowManager(26094): 	at com.pdftron.pdf.utils.Utils$3.run(Utils.java:1881)
E/WindowManager(26094): 	at android.app.Activity.runOnUiThread(Activity.java:6233)
E/WindowManager(26094): 	at com.pdftron.pdf.utils.Utils.showAlertDialog(Utils.java:1876)
E/WindowManager(26094): 	at com.pdftron.pdf.controls.PdfViewCtrlTabHostFragment.handleOpenFileFailed(PdfViewCtrlTabHostFragment.java:4882)
E/WindowManager(26094): 	at com.pdftron.pdf.controls.PdfViewCtrlTabHostFragment.onTabError(PdfViewCtrlTabHostFragment.java:1408)
E/WindowManager(26094): 	at com.pdftron.pdf.controls.PdfViewCtrlTabFragment.handleOpeningDocumentFailed(PdfViewCtrlTabFragment.java:7167)
E/WindowManager(26094): 	at com.pdftron.pdf.controls.PdfViewCtrlTabFragment.handleOpeningDocumentFailed(PdfViewCtrlTabFragment.java:7157)
E/WindowManager(26094): 	at com.pdftron.pdf.controls.PdfViewCtrlTabFragment.openLocalFile(PdfViewCtrlTabFragment.java:6359)
E/WindowManager(26094): 	at com.pdftron.pdf.controls.PdfViewCtrlTabFragment.resumeFragment(PdfViewCtrlTabFragment.java:8334)
E/WindowManager(26094): 	at com.pdftron.pdf.controls.PdfViewCtrlTabFragment.onResume(PdfViewCtrlTabFragment.java:1057)
E/WindowManager(26094): 	at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
E/WindowManager(26094): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
E/WindowManager(26094): 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)

**Comment by sgong-pdftron** [comment]
@xSILENCEx XLS file format is not currently supported. It is on our road map however I do not have an exact timeline at the moment. Thanks.

We will update this ticket when XLS support is added.

**Comment by sgong-pdftron** [comment]
XLS support has been added since PDFTron v8.0.
