### ISSUE TITLE
Support to open & stream PDF from URL

### ISSUE THREAD

**Issue by ductranit** [PDFTron/pdftron-flutter#13]
I look at [this document](https://www.pdftron.com/documentation/ios/guides/viewer/view-online-pdfs/)  
and see that pdftron support to view online pdf as stream. 
I'd expect this library can do lazy load several pages while keep downloading other pages.  But when I use 
```
PdftronFlutter.openDocument("http://homepages.inf.ed.ac.uk/rbf/CVonline/LOCAL_COPIES/TUDELFT/FIP2_3.pdf");
```
 to open the document, the pdf pages can be only displayed when the whole file is downloaded (there is a progress indicator while loading, and I can't view any pages)

**Expected behavior**
The lib can show one or few pages while the rest are downloaded in background

 - Platform:iOS
 - Device: simulator
 - OS: iOS 13

**Comment by JamesTron** [comment]
The viewer will stream a PDF if it has been linearized (saved for "fast web view"). You can do this using PDFTron (native) by saving a document using the `e_linearized` flag. If you open a non-linearized file, then the entire document will need to be downloaded before it can be saved.
