### ISSUE TITLE
Open file from sd card

### ISSUE THREAD

**Issue by deepakcipl** [PDFTron/pdftron-flutter#14]
Please guide how to open file form sd card?

**Comment by sgong-pdftron** [comment]
1. Obtain a file content URI as described by the official guide on Storage access framework (https://developer.android.com/guide/topics/providers/document-provider) -  you might be able to look around for a third party lib that offers this in flutter
2. Pass the content URI obtained in the viewer

Could you give a try?

**Comment by GP4cK** [comment]
Confirmed it works (on Android at least).
It's as simple as:
```dart
import 'dart:io';
//...
final file = File('path/to/file');
final uri = file.uri.toString();
PdftronFlutter.openDocument(uri);
```
