### ISSUE TITLE
(Android) When annot manager is enabled, undoing imported annot causes error

### ISSUE THREAD

**Issue by akwanpdf** [PDFTron/pdftron-flutter#144]
**Describe the bug**
When `annotationManagerEnabled` is true, undoing or redoing an imported annotation causes an error:
```
E/PDFNet: End of input at character 0 of info: {"change": "Merged collaborator's change",'xfdf':'<?xml version="1.0" encoding="UTF-8"?>
    <xfdf __trnAuthorID="myUserId-Mou2dSxy0uqTEKwtEEQ" xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve">
    	<add />
    	<modify />
    	<delete>
    		<id>c684da06-12d2-4ccd-9361-0a1bf2e089e3</id>
    	</delete>
    	<pdf-info import-version="3" version="2" xmlns="http://www.pdftron.com/pdfinfo" />
    </xfdf>'}
```

**Steps to Reproduce the Problem**
1. Go to branch [`annot-manager-enabled-android-bug`](https://github.com/PDFTron/pdftron-flutter/tree/annot-manager-enabled-android-bug).
2. Open and run the example app project in Android Studio, or run from the terminal.
3. In the app, scroll to the second page of the document and observe that the red square annotation has been correctly imported.
4. Press and hold on the undo arrow button on the top right.
5. Press "Undo" in the dropdown.
6. Observe that the red square annotation has been correctly removed from the document. 
7. In the terminal or Logcat, observe the error message: `E/PDFNet: End of input at character 0 of info: ...`
8. The same error occurs when redoing the action.

**Expected behavior**
I expect there to be no error message.

**Screenshots**
The red square annotation on page 2, and the undo button to press.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/83605632/142693124-ed4dcbf5-0086-41a8-abc2-e36b7fb7cb9c.png">

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android
 - Device: Google Pixel 2 XL API 30 virtual device 
 - OS: Android 11.0

**Additional context**
Using Flutter version: 2.5.3
This is happening in both the plugin and the widget.

**Comment by sgong-pdftron** [comment]
@akwanpdf this PR can proceed without this, as the functionality is not affected, the internal error message will be fixed in future releases

**Comment by sgong-pdftron** [comment]
fixed
