### ISSUE TITLE
Bugs in Reflow APIs

### ISSUE THREAD

**Issue by dcupidon** [PDFTron/pdftron-flutter#156]
**Describe the bug**
I found three separate bugs:
1. Disabling images in reflow mode is not working on iOS.
2. Changing the scroll direction of reflow mode is not working on iOS.
3. Vertical scrolling is the default direction although the API documentation for both [iOS](https://www.pdftron.com/api/ios/Classes/PTReflowViewController.html#/c:objc(cs)PTReflowViewController(py)scrollingDirection) and [Android](https://www.pdftron.com/api/android/javadoc/reference/com/pdftron/pdf/config/ViewerConfig.Builder.html#reflowOrientation(int)) states that is horizontal.

**Steps to Reproduce the Problem**
Bugs 1 to 3 (iOS version):
1. Checkout the `reflow-apis` branch.
2. Open the sample app's `main.dart`.
3. Run the app in the iOS simulator.
4. Enable reflow mode and see that an image is present on the first page and that the scrolling direction is vertical.
5. In `main.dart`, set the following viewer configuration options:
```dart
config.reflowOrientation = ReflowOrientation.horizontal;
config.imageInReflowModeEnabled = false;
```
6. Hot reload or rebuild the app.
7. See that the image is still present and the scrolling direction remains the vertical.

Bugs 3 (Android version):
1. Checkout the `reflow-apis` branch.
2. Run the app in the Android simulator.
3. Enable reflow mode and see that the scrolling direction is vertical.

**Expected behaviour**
1. The value of `reflowOrientation` should control the scroll direction of the reflow mode on iOS.
2. The value of `imageInReflowModeEnabled` should control whether images are shown in reflow mode on iOS.
3. Horizontal scrolling being the default direction for reflow mode.

**Platform/Device Information**
 - Platform: iOS and Android
 - Device: iPod touch 7th generation and Pixel 3a (x86)
 - OS: iOS 14.4 and Android API 30

**Additional context**
Bugs 1 and 3 were noticed on React Native. The presence of bug 2 on React Native could not be confirmed because the `reflowOrientation` API for iOS does not exist in that library.

**Comment by sgong-pdftron** [comment]
3 is a documentation error, the scroll direction should follow viewer's scroll direction, i.e. viewer is vertical then reflow is vertical, viewer is horizontal then reflow is horizontal

**Comment by dcupidon** [comment]
I have created a [PR](https://github.com/PDFTron/pdftron-react-native/pull/429) that updates the React Native documentation of `reflowOrientation` and adds the iOS implementation of the prop. I can now confirm that bug 2 is present in React Native.

**Comment by dcupidon** [comment]
A fix for bug 1 has been added to the native iOS library, a fix for bug 2 will come at a later date.
