### ISSUE TITLE
App can't compile due to NullPointerException

### ISSUE THREAD

**Issue by aswathinamb** [PDFTron/pdftron-flutter#164]
1)	Clone the example project for pdftron from the below link : 
https://github.com/PDFTron/pdftron-flutter/tree/master/example.
Tried compiling the above project.

**Expected results**: Should be able to view the pdf document provided in the example.

**Actual results**:
FAILURE: Build failed with an exception.

_Error in Console_:
E/MethodChannel#pdftron_flutter(26254): Failed to handle method call
E/MethodChannel#pdftron_flutter(26254): java.lang.NullPointerException
E/MethodChannel#pdftron_flutter(26254): 	at java.util.Objects.requireNonNull(Objects.java:203)
E/MethodChannel#pdftron_flutter(26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.checkFunctionPrecondition(PluginUtils.java:3300)
E/MethodChannel#pdftron_flutter(26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.onMethodCall(PluginUtils.java:1950)
E/MethodChannel#pdftron_flutter(26254): 	at com.pdftron.pdftronflutter.helpers.PluginMethodCallHandler.onMethodCall(PluginMethodCallHandler.java:276)
E/MethodChannel#pdftron_flutter(26254): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#pdftron_flutter(26254): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#pdftron_flutter(26254): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#pdftron_flutter(26254): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#pdftron_flutter(26254): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#pdftron_flutter(26254): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#pdftron_flutter(26254): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#pdftron_flutter(26254): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#pdftron_flutter(26254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#pdftron_flutter(26254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/MethodChannel#pdftron_flutter(26254): Failed to handle method call
E/MethodChannel#pdftron_flutter(26254): java.lang.NullPointerException
E/MethodChannel#pdftron_flutter(26254): 	at java.util.Objects.requireNonNull(Objects.java:203)
E/MethodChannel#pdftron_flutter(26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.checkFunctionPrecondition(PluginUtils.java:3300)
E/MethodChannel#pdftron_flutter(26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.onMethodCall(PluginUtils.java:1961)
E/MethodChannel#pdftron_flutter(26254): 	at com.pdftron.pdftronflutter.helpers.PluginMethodCallHandler.onMethodCall(PluginMethodCallHandler.java:276)
E/MethodChannel#pdftron_flutter(26254): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#pdftron_flutter(26254): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#pdftron_flutter(26254): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#pdftron_flutter(26254): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#pdftron_flutter(26254): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#pdftron_flutter(26254): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#pdftron_flutter(26254): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#pdftron_flutter(26254): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#pdftron_flutter(26254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#pdftron_flutter(26254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/MethodChannel#pdftron_flutter(26254): Failed to handle method call
E/MethodChannel#pdftron_flutter(26254): java.lang.NullPointerException
E/MethodChannel#pdftron_flutter(26254): 	at java.util.Objects.requireNonNull(Objects.java:203)
E/MethodChannel#pdftron_flutter(26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.checkFunctionPrecondition(PluginUtils.java:3300)
E/MethodChannel#pdftron_flutter(26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.onMethodCall(PluginUtils.java:1972)
E/MethodChannel#pdftron_flutter(26254): 	at com.pdftron.pdftronflutter.helpers.PluginMethodCallHandler.onMethodCall(PluginMethodCallHandler.java:276)
E/MethodChannel#pdftron_flutter(26254): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#pdftron_flutter(26254): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#pdftron_flutter(26254): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#pdftron_flutter(26254): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#pdftron_flutter(26254): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#pdftron_flutter(26254): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#pdftron_flutter(26254): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#pdftron_flutter(26254): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#pdftron_flutter(26254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#pdftron_flutter(26254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/EGL_emulation(26254): eglMakeCurrent: 0xe1005b40: ver 2 0 (tinfo 0xe1003ea0)
D/EGL_emulation(26254): eglMakeCurrent: 0xe1005b40: ver 2 0 (tinfo 0xe1003ea0)
D/EGL_emulation(26254): eglMakeCurrent: 0xe1005b40: ver 2 0 (tinfo 0xe1003ea0)
D/EGL_emulation(26254): eglMakeCurrent: 0xe1005b40: ver 2 0 (tinfo 0xe1003ea0)
D/EGL_emulation(26254): eglMakeCurrent: 0xdf773660: ver 2 0 (tinfo 0xcdbe4ae0)
E/flutter (26254): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter (26254): 	at java.util.Objects.requireNonNull(Objects.java:203)
E/flutter (26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.checkFunctionPrecondition(PluginUtils.java:3300)
E/flutter (26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.onMethodCall(PluginUtils.java:1950)
E/flutter (26254): 	at com.pdftron.pdftronflutter.helpers.PluginMethodCallHandler.onMethodCall(PluginMethodCallHandler.java:276)
E/flutter (26254): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (26254): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (26254): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (26254): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26254): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (26254): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (26254): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter (26254): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (26254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (26254): )
E/flutter (26254): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (26254): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (26254): <asynchronous suspension>
E/flutter (26254): 
E/flutter (26254): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter (26254): 	at java.util.Objects.requireNonNull(Objects.java:203)
E/flutter (26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.checkFunctionPrecondition(PluginUtils.java:3300)
E/flutter (26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.onMethodCall(PluginUtils.java:1961)
E/flutter (26254): 	at com.pdftron.pdftronflutter.helpers.PluginMethodCallHandler.onMethodCall(PluginMethodCallHandler.java:276)
E/flutter (26254): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (26254): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (26254): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (26254): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26254): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (26254): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (26254): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter (26254): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (26254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (26254): )
E/flutter (26254): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (26254): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (26254): <asynchronous suspension>
E/flutter (26254): 
E/flutter (26254): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter (26254): 	at java.util.Objects.requireNonNull(Objects.java:203)
E/flutter (26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.checkFunctionPrecondition(PluginUtils.java:3300)
E/flutter (26254): 	at com.pdftron.pdftronflutter.helpers.PluginUtils.onMethodCall(PluginUtils.java:1972)
E/flutter (26254): 	at com.pdftron.pdftronflutter.helpers.PluginMethodCallHandler.onMethodCall(PluginMethodCallHandler.java:276)
E/flutter (26254): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (26254): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (26254): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (26254): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26254): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (26254): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (26254): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter (26254): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (26254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (26254): )
E/flutter (26254): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (26254): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (26254): <asynchronous suspension>
E/flutter (26254): #2      _ViewerState.showViewer (package:pdftron_flutter_example/main.dart:149:16)
E/flutter (26254): <asynchronous suspension>
E/flutter (26254): 
D/EGL_emulation(26254): eglMakeCurrent: 0xdf773660: ver 2 0 (tinfo 0xcdbe4ae0)
D/EGL_emulation(26254): eglMakeCurrent: 0xe1005b40: ver 2 0 (tinfo 0xe1003ea0)
D/EGL_emulation(26254): eglMakeCurrent: 0xe1005b40: ver 2 0 (tinfo 0xe1003ea0)
E/WindowManager(26254): 
E/WindowManager(26254): android.view.WindowLeaked: Activity com.pdftron.pdftronflutter.FlutterDocumentActivity has leaked window DecorView@71affe6[FlutterDocumentActivity] that was originally added here
E/WindowManager(26254): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:511)
E/WindowManager(26254): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
E/WindowManager(26254): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
E/WindowManager(26254): 	at android.app.Dialog.show(Dialog.java:329)
E/WindowManager(26254): 	at com.pdftron.pdf.utils.Utils.safeShowAlertDialog(Utils.java:1983)
E/WindowManager(26254): 	at com.pdftron.pdf.utils.Utils$3.run(Utils.java:2014)
E/WindowManager(26254): 	at android.app.Activity.runOnUiThread(Activity.java:6282)
E/WindowManager(26254): 	at com.pdftron.pdf.utils.Utils.showAlertDialog(Utils.java:2009)
E/WindowManager(26254): 	at com.pdftron.pdf.controls.PdfViewCtrlTabHostBaseFragment.handleOpenFileFailed(PdfViewCtrlTabHostBaseFragment.java:4440)
E/WindowManager(26254): 	at com.pdftron.pdf.controls.PdfViewCtrlTabHostBaseFragment.onTabError(PdfViewCtrlTabHostBaseFragment.java:1371)
E/WindowManager(26254): 	at com.pdftron.pdf.controls.PdfViewCtrlTabBaseFragment.handleOpeningDocumentFailed(PdfViewCtrlTabBaseFragment.java:7764)
E/WindowManager(26254): 	at com.pdftron.pdf.controls.PdfViewCtrlTabBaseFragment.handleOpeningDocumentFailed(PdfViewCtrlTabBaseFragment.java:7754)
E/WindowManager(26254): 	at com.pdftron.pdf.controls.PdfViewCtrlTabBaseFragment.onDownloadEvent(PdfViewCtrlTabBaseFragment.java:1883)
E/WindowManager(26254): 	at com.pdftron.pdf.PDFViewCtrl$e.handleMessage(SourceFile:12685)
E/WindowManager(26254): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/WindowManager(26254): 	at android.os.Looper.loop(Looper.java:193)
E/WindowManager(26254): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/WindowManager(26254): 	at java.lang.reflect.Method.invoke(Native Method)
E/WindowManager(26254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/WindowManager(26254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**flutter doctor -v**
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale en-US)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\qwsd\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)

• No issues found!

**Comment by akwanpdf** [comment]
Thanks for posting. We have cloned the repo but haven't been able to replicate the issue just by running the app.

The error you posted does occur when the widget and plugin are mixed in `lib/main.dart`. For example, if you are using the plugin, all viewer methods should be called using `PdftronFlutter` instead of `controller`, otherwise that error will occur. Likewise, if you are using the widget, all viewer methods should be called using `controller`, not `PdftronFlutter`. 

Could you please check your `lib/main.dart` and see if you've made any such edits?

**Comment by aswathinamb** [comment]
Did not make any additional changes to main.dart file. Below is the code snippet from the file. 
 Running the below main.dart file.


`import 'dart:async';
import 'dart:io' show Platform;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pdftron_flutter/pdftron_flutter.dart';
// Uncomment this if you are using local files
// import 'package:permission_handler/permission_handler.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Viewer(),
    );
  }
}

class Viewer extends StatefulWidget {
  @override
  _ViewerState createState() => _ViewerState();
}

class _ViewerState extends State<Viewer> {
  String _version = 'Unknown';
  String _document =
      "https://pdftron.s3.amazonaws.com/downloads/pl/PDFTRON_mobile_about.pdf";
  bool _showViewer = true;

  @override
  void initState() {
    super.initState();
    initPlatformState();

    showViewer();

    // If you are using local files delete the line above, change the _document field
    // appropriately and uncomment the section below.
    // if (Platform.isIOS) {
      // // Open the document for iOS, no need for permission.
      // showViewer();
    // } else {
      // // Request permission for Android before opening document.
      // launchWithPermission();
    // }
  }

  // Future<void> launchWithPermission() async {
  //  PermissionStatus permission = await Permission.storage.request();
  //  if (permission.isGranted) {
  //    showViewer();
  //  }
  // }

  // Platform messages are asynchronous, so initialize in an async method.
  Future<void> initPlatformState() async {
    String version;
    // Platform messages may fail, so use a try/catch PlatformException.
    try {
      // Initializes the PDFTron SDK, it must be called before you can use any functionality.
      PdftronFlutter.initialize("your_pdftron_license_key");

      version = await PdftronFlutter.version;
    } on PlatformException {
      version = 'Failed to get platform version.';
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, you want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      _version = version;
    });
  }

  void showViewer() async {
    // opening without a config file will have all functionality enabled.
    // await PdftronFlutter.openDocument(_document);

    var config = Config();
    // How to disable functionality:
    //      config.disabledElements = [Buttons.shareButton, Buttons.searchButton];
    //      config.disabledTools = [Tools.annotationCreateLine, Tools.annotationCreateRectangle];
    // Other viewer configurations:
    //      config.multiTabEnabled = true;
    //      config.customHeaders = {'headerName': 'headerValue'};

    // An event listener for document loading
    var documentLoadedCancel = startDocumentLoadedListener((filePath) {
      print("document loaded: $filePath");
    });

    await PdftronFlutter.openDocument(_document, config: config);

    try {
      // The imported command is in XFDF format and tells whether to add, modify or delete annotations in the current document.
      PdftronFlutter.importAnnotationCommand(
          "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
              "    <xfdf xmlns=\"http://ns.adobe.com/xfdf/\" xml:space=\"preserve\">\n" +
              "      <add>\n" +
              "        <square style=\"solid\" width=\"5\" color=\"#E44234\" opacity=\"1\" creationdate=\"D:20200619203211Z\" flags=\"print\" date=\"D:20200619203211Z\" name=\"c684da06-12d2-4ccd-9361-0a1bf2e089e3\" page=\"1\" rect=\"113.312,277.056,235.43,350.173\" title=\"\" />\n" +
              "      </add>\n" +
              "      <modify />\n" +
              "      <delete />\n" +
              "      <pdf-info import-version=\"3\" version=\"2\" xmlns=\"http://www.pdftron.com/pdfinfo\" />\n" +
              "    </xfdf>");
    } on PlatformException catch (e) {
      print("Failed to importAnnotationCommand '${e.message}'.");
    }

    try {
      // Adds a bookmark into the document.
      PdftronFlutter.importBookmarkJson('{"0":"Page 1"}');
    } on PlatformException catch (e) {
      print("Failed to importBookmarkJson '${e.message}'.");
    }

    // An event listener for when local annotation changes are committed to the document.
    // xfdfCommand is the XFDF Command of the annotation that was last changed.
    var annotCancel = startExportAnnotationCommandListener((xfdfCommand) async {
      String command = xfdfCommand;
      print("flutter xfdfCommand:\n");
      // Dart limits how many characters are printed onto the console. 
      // The code below ensures that all of the XFDF command is printed.
      if (command.length > 1024) {
        int start = 0;
        int end = 1023;
        while (end < command.length) {
          print(command.substring(start, end) + "\n");
          start += 1024;
          end += 1024;
        }
        print(command.substring(start));
      } else {
        print(command);
      }
    });

    // An event listener for when local bookmark changes are committed to the document.
    // bookmarkJson is JSON string containing all the bookmarks that exist when the change was made.
    var bookmarkCancel = startExportBookmarkListener((bookmarkJson) {
      print("flutter bookmark: $bookmarkJson");
    });

    var path = await PdftronFlutter.saveDocument();
    print("flutter save: $path");

    // To cancel event:
    // annotCancel();
    // bookmarkCancel();
    // documentLoadedCancel();
  }

  @override
  Widget build(BuildContext context) {
    // If using Android Widget, uncomment one of the following:
    // If using Flutter v2.3.0-17.0.pre or earlier.
    // SystemChrome.setEnabledSystemUIOverlays(
    //   SystemUiOverlay.values
    // );
    // If using later Flutter versions.
    // SystemChrome.setEnabledSystemUIMode(
    //   SystemUiMode.edgeToEdge,
    // );
    
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        child:
            // Uncomment this to use Widget version of the viewer.
            // _showViewer
            // ? SafeArea (
            //   child: DocumentView(
            //     onCreated: _onDocumentViewCreated,
            //   )):
            Container(),
      ),
    );
  }

  // This function is used to control the DocumentView widget after it has been created.
  // The widget will not work without a void Function(DocumentViewController controller) being passed to it.
  void _onDocumentViewCreated(DocumentViewController controller) async {
    Config config = new Config();

    var leadingNavCancel = startLeadingNavButtonPressedListener(() {
      // Uncomment this to quit the viewer when leading navigation button is pressed.
      // this.setState(() {
      //   _showViewer = !_showViewer;
      // });

      // Show a dialog when leading navigation button is pressed.
      _showMyDialog();
    });

    controller.openDocument(_document, config: config);
  }

  Future<void> _showMyDialog() async {
    print('hello');
    return showDialog<void>(
      context: context,
      barrierDismissible: false, // User must tap button!
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('AlertDialog'),
          content: SingleChildScrollView(
            child: Text('Leading navigation button has been pressed.'),
          ),
          actions: <Widget>[
            TextButton(
              child: Text('OK'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
          ],
        );
      },
    );
  }
}`

**Comment by akwanpdf** [comment]
The latest official version of [`lib/main.dart` on GitHub](https://github.com/PDFTron/pdftron-flutter/blob/master/example/lib/main.dart) has some differences from the code you pasted. For example, the official version uses:
- `class _ViewerState extends State<Viewer>` instead of `class _ViewerState extends State`
- `@override` instead of `@OverRide` (the latter causes a build error: `Error: Getter not found: 'OverRide'.`)

Can you try using the official [`lib/main.dart`](https://github.com/PDFTron/pdftron-flutter/blob/master/example/lib/main.dart)? Also, what version of `pdftron_flutter` is written in your `pubspec.yaml`?

**Comment by aswathinamb** [comment]
updated the main.dart as per the same. Still facing the same issue. I have added the below dependency in the pubspec.yaml.

pdftron_flutter: ^1.0.0-beta.3

**Comment by dcupidon** [comment]
After running the example app on both the latest version (`master` branch) and version 1.0.0-beta.3, we have yet to encounter the issue you are faced with. We will continue trying to reproduce the issue.

In the meantime, could you debug the example app in Android Studio. Place your breakpoint at the start of `onMethodCall()` in `PluginMethodCallHandler.java` and step through the code. If the app does crash, could you let us know at which point it does?

**Comment by sgong-pdftron** [comment]
closed due to inactivity
