### ISSUE TITLE
[Android] Export/Import Annotation Command does not work properly when Annotation Manager is not enabled

### ISSUE THREAD

**Issue by ama-pdftron** [PDFTron/pdftron-flutter#176]
**Describe the bug**
https://support.pdftron.com/a/tickets/27079

**Steps to Reproduce the Problem**
1. Use `startExportAnnotationCommandListener` and `importAnnotationCommand` in tandem
2. Duplicate annotation created (looks like another unique ID is generated instead of updating the old one)
3. Above steps do not happen when AnnotationManagerEnabled is set to true, but in theory it should work without it

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel, please report issues through our official channel at https://apryse.com/support
