### ISSUE TITLE
App Bundle size increased by 86.2 MBs by including PDFTron

### ISSUE THREAD

**Issue by jitendrapurohit12** [PDFTron/pdftron-flutter#191]
I am using PDFTron plugin for my app and previously my app bundle size was 21.7 MBs and after inclusion of this plugin the size increased to 107.9 MBs. As I'm already using app bundles using Split APKs is of no use. I'm using latest version 1.0.0-beta.4

 - Platform: Android
 - Device: POCO F1
 - OS: Android 12

**Comment by sgong-pdftron** [comment]
Hi, if you are splitting properly, you should see sizes similar to this table:
https://www.pdftron.com/documentation/android/faq/full-vs-standard/

Could you please re-visit how you are splitting the API by native architecture?
See guide here: https://www.pdftron.com/documentation/android/faq/reduce-apk-size/

Thanks.
