### ISSUE TITLE
App can't compile due to PDFTRON ERROR

### ISSUE THREAD

**Issue by charlesarchibong** [PDFTron/pdftron-flutter#20]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.transistorsoft:tsbackgroundfetch:+.
     Required by:
         project :app > project :background_fetch
      > Failed to list versions for com.transistorsoft:tsbackgroundfetch.
         > Unable to load Maven meta-data from https://pdftron-maven.s3.amazonaws.com/release/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml.
            > Could not get resource 'https://pdftron-maven.s3.amazonaws.com/release/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'.
               > Could not GET 'https://pdftron-maven.s3.amazonaws.com/release/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 31s
Exception: Gradle task assembleDebug failed with exit code 1

# flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by sgong-pdftron** [comment]
@charlesarchibong could you try to run the sample project: https://github.com/PDFTron/pdftron-flutter/tree/master/example? Are you able to run this? Thanks.

**Comment by charlesarchibong** [comment]
Yeah, I was able to fix the issue.
