### ISSUE TITLE
fillAndSign on iOS

### ISSUE THREAD

**Issue by Moussabaddour** [PDFTron/pdftron-flutter#203]
Hi,

I am trying to customize the pdf view and hide some no-needed tools.
All the tools can be hidden except fillAndSign.
-----
var hideDefaultAnnotationToolbars = [ DefaultToolbars.fillAndSign ];
config.hideDefaultAnnotationToolbars = hideDefaultAnnotationToolbars;
----
BR

**Comment by sgong-pdftron** [comment]
Hi @Moussabaddour could you please share a complete snippet of your code, the current behaviour (as PNG) and describe the expected behaviour? Thanks.

**Comment by Moussabaddour** [comment]
this is my code

<img width="281" alt="fiilAndSign" src="https://user-images.githubusercontent.com/45218852/157768001-4870997a-f0f4-4673-8c06-3833c31e304b.PNG">

**Comment by Moussabaddour** [comment]
This is the output
<img width="236" alt="currentOutput" src="https://user-images.githubusercontent.com/45218852/157768069-cfc0282e-8805-446f-a898-7a976fe0de61.PNG">

**Comment by Moussabaddour** [comment]
I expect the app will show only "View".....!!!!???

BR

**Comment by Moussabaddour** [comment]
The problem is only on iOS

**Comment by Moussabaddour** [comment]
fixed by adding this line  to PTFlutterDocumentController.m at line 1423 

PTAnnotationToolbarFillAndSign: toolGroupManager.fillAndSignItemGroup,

maybe I have old clone.

BR
