### ISSUE TITLE
Document Annotations and Comments is not persisted

### ISSUE THREAD

**Issue by charlesarchibong** [PDFTron/pdftron-flutter#22]
When I add Annotations and Comments to a document, they are not persisted ie when the document is closed and reopen, the data are gone.

**Comment by sgong-pdftron** [comment]
@charlesarchibong what is the file source you are using? are you opening a local file or HTTP/HTTPS?

**Comment by charlesarchibong** [comment]
> @charlesarchibong what is the file source you are using? are you opening a local file or HTTP/HTTPS?

https.

**Comment by sgong-pdftron** [comment]
@charlesarchibong right, for HTTP/HTTPS we usually recommend having annotation saved separate from the document via import/export annotation command. Could you describe your use case and whether this will work for you? Thanks.

**Comment by charlesarchibong** [comment]
> @charlesarchibong right, for HTTP/HTTPS we usually recommend having annotation saved separate from the document via import/export annotation command. Could you describe your use case and whether this will work for you? Thanks.

How is this possible with flutter and the PDFTron library has only 2 method initial and openDocument

**Comment by sgong-pdftron** [comment]
@charlesarchibong 
If you update to the latest version you will see 2 new API to sync annotations and user bookmarks, as well as callback for sending info out. Could you check?

**Comment by charlesarchibong** [comment]
> @charlesarchibong
> If you update to the latest version you will see 2 new API to sync annotations and user bookmarks, as well as callback for sending info out. Could you check?

I have seen it, please can you explain to me the whole process involve, how to persist this annotation and comments and how to retrieve it with the method please. Thank you in advance.

**Comment by sgong-pdftron** [comment]
@charlesarchibong this is getting more complicated now and I need to know more about your use case. Could you please submit a support ticket here instead: https://www.pdftron.com/form/request/. I will close this issue now. And let's continue discussion with a new support ticket. Thanks!

**Comment by charlesarchibong** [comment]
Hmmm
