### ISSUE TITLE
Save a PDF file with the annotations and email it

### ISSUE THREAD

**Issue by bbozhidarov** [PDFTron/pdftron-flutter#23]
Hello, I could not find an answer to that question, so any help would be appreciated.

What I'm trying to do is the following: generate a PDF file with some data, open it with PDFTron, put some annotations and then save the file with the annotations and email it. Saving the annotations merged in a new pdf file should happen programmatically. Is that possible with the Flutter SDK.

I successfully generate a file using the pdf library for dart, then save it to temp folder, open it in the PDFTron annotator, but then I don't see a way to programmatically merge the annotations in the file and email it.

**Comment by sgong-pdftron** [comment]
@bbozhidarov the viewer comes with share icon that will allow you to email with the annotations already. Does that work for you? Share icon is the standard share icon that is familiar to the platform, should locate in the top toolbar. Could you try?

**Comment by bbozhidarov** [comment]
@sgong-pdftron Thanks for your reply! Unfortunatelly that doesn't work for our use case. We need to email the annotated PDF programmatically. Is that possible?

**Comment by sgong-pdftron** [comment]
@bbozhidarov no problem, we will be adding a new API that will save the document and return you the absolute file path, will that work for you? thanks

**Comment by bbozhidarov** [comment]
Yes, that would work. Thanks a lot!
