### ISSUE TITLE
Compile issue in android flutter

### ISSUE THREAD

**Issue by abdulhaseeb725** [PDFTron/pdftron-flutter#233]
Getting this error while trying to build android in flutter. Working fine on IOS.
* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.pdftron:pdftron:9.2.4-beta01.
     Required by:
         project :app > project :pdftron_flutter
      > Could not resolve com.pdftron:pdftron:9.2.4-beta01.
         > Could not get resource 'https://google.bintray.com/exoplayer/com/pdftron/pdftron/9.2.4-beta01/pdftron-9.2.4-beta01.pom'.
            > Could not HEAD 'https://google.bintray.com/exoplayer/com/pdftron/pdftron/9.2.4-beta01/pdftron-9.2.4-beta01.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve com.pdftron:tools:9.2.4-beta01.
     Required by:
         project :app > project :pdftron_flutter
      > Could not resolve com.pdftron:tools:9.2.4-beta01.
         > Could not get resource 'https://google.bintray.com/exoplayer/com/pdftron/tools/9.2.4-beta01/tools-9.2.4-beta01.pom'.
            > Could not HEAD 'https://google.bintray.com/exoplayer/com/pdftron/tools/9.2.4-beta01/tools-9.2.4-beta01.pom'. Received status code 502 from server: Bad Gateway

**Comment by sgong-pdftron** [comment]
Hi @abdulhaseeb725 I would recommend you to try to do a clean and rebuild. From the error message it seems like the resource search path is the problem and another third party library you are using "exoplayer" somehow is identified as resource search path of PDFTron.

**Comment by abdulhaseeb725** [comment]
> Hi @abdulhaseeb725 I would recommend you to try to do a clean and rebuild. From the error message it seems like the resource search path is the problem and another third party library you are using "exoplayer" somehow is identified as resource search path of PDFTron.

Yes a clean installatino solve the problem. Thanks
