### ISSUE TITLE
Could not get unknown property 'PDFTRON_LICENSE_KEY'  error on build

### ISSUE THREAD

**Issue by liveaffiliates** [PDFTron/pdftron-flutter#246]
**Describe the bug**
* What went wrong:

A problem occurred evaluating project ':app'.
> Could not get unknown property 'PDFTRON_LICENSE_KEY' for DefaultConfig$AgpDecorated_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=21, mCodename='null'}, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=BLANKEDOUTFORPRIVACY, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=[], buildConfigFields={}, resValues={}, proguardFiles=[], consumerProguardFiles=[], manifestPlaceholders={applicationName=android.app.Application}, wearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig$AgpDecorated.

**Steps to Reproduce the Problem**

**Expected behavior**

**Screenshots**

**Platform/Device Information (please complete the following information if applicable):**
Android

**Additional context**
Hi we had pdftron working fine since the last update your sales rep is not available for a month so we cant get a licence until he returns. We have the commercial for our web app already. Today we tried to build, it was working last night , no changes and now we are getting this error. any help would be greatly appreciated thanks

**Comment by ama-pdftron** [comment]
Hi @liveaffiliates 

Have you followed the Android steps in our setup guide?
https://github.com/PDFTron/pdftron-flutter#android

Please be aware you still need to declare the `PDFTRON_LICENSE_KEY` properties even if you do not currently have a license key.

Thanks,
Andrew.

**Comment by liveaffiliates** [comment]
> Hi @liveaffiliates
> 
> Have you followed the Android steps in our setup guide? https://github.com/PDFTron/pdftron-flutter#android
> 
> Please be aware you still need to declare the `PDFTRON_LICENSE_KEY` properties even if you do not currently have a license key.
> 
> Thanks, Andrew.

@ama-pdftron 

Hi Andrew, Yes we followed the guide. It was working before the latest roll out and nothing was changed. We have also found an issue in the latest ios rollout and had to rollback to previous version. Unfortunately this has not worked for android.

Thanks

Nick
