### ISSUE TITLE
CocoaPods could not find compatible versions for pod "PDFNet":

### ISSUE THREAD

**Issue by CommniaOliver** [PDFTron/pdftron-flutter#249]
[!] CocoaPods could not find compatible versions for pod "PDFNet":
      In snapshot (Podfile.lock):
        PDFNet (from `https://www.pdftron.com/downloads/ios/cocoapods/xcframeworks/pdfnet/latest.podspec`)

**Steps to Reproduce the Problem**
running "pod install"

ios

**Comment by zhoulijun12315** [comment]
i got the same issue.  @terryyoon-pdftron

**Comment by terryyoon-pdftron** [comment]
Hey there, could you please try deleting `Pods` and `Podfile.lock`, cleaning Pod cache, and running `pod install` again?
```
rm -rf Pods Podfile.lock
pod cache clean --all
pod install
```
Let us know again if the issue persists.

**Comment by RatheeshSivaraman** [comment]
@terryyoon-pdftron Am facing the same issue in **flutter-ios**, when i try to install pod (pod install) in terminal, getting the below error.
**[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/admin/work/project/xxxx/ios/Pods/PDFNet/Tools.xcframework)'**.
I have tried all possible cleaning (flutter clean, pod clean cache), but nothing seems to be worked.

**Comment by terryyoon-pdftron** [comment]
Hey, would you mind providing us with some additional information that could help us reproduce the issue? (your `pubspec.yaml` file, your CocoaPods version, etc.)
