### ISSUE TITLE
Watermark not removing.

### ISSUE THREAD

**Issue by AbdulHaseeb090** [PDFTron/pdftron-flutter#257]
I have purchased the license key for Android, IOS and MAC. But even when I entered the license key it still shows watermark of pdftron. I am using pdftron_flutter (1.0.0-beta.1) version. I cannot use latest version due to some issues with other libraries in flutter.

**Comment by darrenchann** [comment]
Hi @AbdulHaseeb090,

Please look into opening a support ticket as this may be a private license key matter that may be more appropriate for privacy concerns.

Refer to our contact page to open a freshdesk ticket:
https://www.pdftron.com/company/contact-us/
