### ISSUE TITLE
NOT WORKING ON PIXEL 4A

### ISSUE THREAD

**Issue by AbdulHaseeb70** [PDFTron/pdftron-flutter#259]
Hi. I am using pdftron_flutter package it's working fine on both android and Ios devices. Bit it's not working on Google Pixel 4A. Pdf opens but I am unable to perform any action except scroll and zoom in out. Even leading navigation options doesn't work.

It's only happening on Google Pixel 4A.
- [ ] It's working fine on other android devices with android 12.

**Comment by darrenchann** [comment]
Hi @AbdulHaseeb70,

I've tried replicating your issue on an emulated Pixel 4a and other devices and my physical device, however, was not able to reproduce this issue. Would you be able to provide a video and any console errors that may have come up?

Also, is this a physical or an emulated Pixel 4a device?

**Comment by AbdulHaseeb090** [comment]
> Hi @AbdulHaseeb70,
> 
> I've tried replicating your issue on an emulated Pixel 4a and other devices and my physical device, however, was not able to reproduce this issue. Would you be able to provide a video and any console errors that may have come up?
> 
> Also, is this a physical or an emulated Pixel 4a device?

Hi, I used the exact same code example available on this repo with valid license key. Yes I used physical Pixel 4A device.

**Comment by darrenchann** [comment]
> > Hi @AbdulHaseeb70,
> > I've tried replicating your issue on an emulated Pixel 4a and other devices and my physical device, however, was not able to reproduce this issue. Would you be able to provide a video and any console errors that may have come up?
> > Also, is this a physical or an emulated Pixel 4a device?
> 
> Hi, I used the exact same code example available on this repo with valid license key. Yes I used physical Pixel 4A device.

In order for us to address your issue, would you be able to provide a video and code sample of your project that shows this error?
