### ISSUE TITLE
Pdftron Direct MS Office document viewing and conversion

### ISSUE THREAD

**Issue by adiShinwari** [PDFTron/pdftron-flutter#264]
Hey, I am using pdftron in my project and I am new to flutter. I want to add conversion features in my app like pdf to doc and vice versa, but I am unable to find anything related to that in the documentation.

**Comment by adiShinwari** [comment]
Thank you @darrenchann 

can't I convert the pdf to office without opening(viewing) the pdf document?

**Comment by darrenchann** [comment]
Hi @adiShinwari 

We can add a feature request into our backlog to add an API for PDF-to-Office conversion and update you when we have done so for you.

**Comment by adiShinwari** [comment]
sorry @darrenchann 
I was trying to say, that can't I convert the office (doc, Docx, pptx) to pdf without opening(viewing) the file in Viewer? I converted the doc file to pdf when the file was open in the viewer. But I want to add this functionality without opening the file.

**Comment by darrenchann** [comment]
@adiShinwari
We understand, however, this functionality is not supported at the moment and we can add such API for you. 

We will update you once this is ready for you to try.

**Comment by adiShinwari** [comment]
Okay, so I want that one functionality and also if it is possible to have pdf to other office files. Like pdf to doc, etc.

**Comment by darrenchann** [comment]
PDF to office is not supported. You can look to use our server side API for it:
https://www.pdftron.com/documentation/core/guides/features/conversion/convert-pdf-to-word/

**Comment by adiShinwari** [comment]
these are in native code. How can I Implement it in flutter? Please help me with that.

**Comment by sgong-pdftron** [comment]
@adiShinwari Please note that server side API means it is **not** available on our Flutter SDK, you will need to implement a **server**.

**Comment by adiShinwari** [comment]
@sgong-pdftron Is there any guide or tuttorial for it. I have never done it before.

**Comment by darrenchann** [comment]
@adiShinwari 
All of the server side guides and samples are located at the links below:

Windows Server: https://www.pdftron.com/documentation/windows/get-started/
Linux Server: https://www.pdftron.com/documentation/linux/get-started/

**Comment by adiShinwari** [comment]
@darrenchann  thank you.
