### ISSUE TITLE
Not able to save a copy of a document from "Save a Copy" option.

### ISSUE THREAD

**Issue by ramsmart-inno** [PDFTron/pdftron-flutter#275]
Save as PDF will work in the Print option. But it does not save a copy option is not working.

**Comment by darrenchann** [comment]
Hi @ramsmart-inno 

I was not able to reproduce any issue with our "save a copy" tool in our flutter sample.

Please look to this device path if you're running our app in the emulator to see your saved copies:
/data/data/com.pdftron.pdftronflutterexample/files/recently_used_cache

I confirmed the changes by saving the copy over and over and seeing the viewer refresh and open the copy after it was opened:
![image](https://user-images.githubusercontent.com/15988850/201999190-1ec58fe6-3d2a-4c78-8c88-561320db2b7b.png)

We used our sample project, so if this is your own project would you be able to provide a sample of your project?

**Comment by ramsmart-inno** [comment]
Using sample project which get from git. 
How to save the pdf in local storage in downloads or custom path from "save a copy".  
I don't want to save a cache.
And how can add qr code in pdf automatically.

check the below images.

![WhatsApp Image 2022-11-16 at 8 27 18 AM](https://user-images.githubusercontent.com/72604311/202072685-7b23a4b3-03ef-43e9-b4a9-26eede06d4eb.jpeg)
![WhatsApp Image 2022-11-16 at 8 27 17 AM (1)](https://user-images.githubusercontent.com/72604311/202072691-4dbcf3e0-bad8-4f2c-ad42-33a79620de2b.jpeg)
![WhatsApp Image 2022-11-16 at 8 27 17 AM](https://user-images.githubusercontent.com/72604311/202072695-4ff30d4d-2e79-4bf6-880f-4b9a04e420c9.jpeg)

**Comment by Tyler-Gordon** [comment]
Hello @ramsmart-inno,

Can you please open a support ticket here: https://www.pdftron.com/form/trial-support/ so we can better assist you with this issue.
