### ISSUE TITLE
PageViewMode and FitMode Adjustments after Document is opened

### ISSUE THREAD

**Issue by leo-neon** [PDFTron/pdftron-flutter#276]
BUG / MISSING FUNCTIONALITY
Currently, you can just pass the PageViewMode and FitMode to the config at the beginning. You cannot manipulate them after document is opened.

EXPECTED
It would be very nice to have some functions on the DocumentViewController like setPageViewMode() or setFitMode() to adjust these things in advance.

ADDITIONAL CONTEXT 
For example, I have an orientation listener and I want to set these values according to portrait (Single Page) and landscape (Facing Pages).

**Comment by ama-pdftron** [comment]
Hello leo-neon,

Thanks for the feedback! We have added this to our backlog as a feature request.

**Comment by sgong-pdftron** [comment]
We are closing down issues section in favor of official Apryse support channel, please report issues through our official channel at https://apryse.com/support
