### ISSUE TITLE
appComponentFactory AndroidManifest issue

### ISSUE THREAD

**Issue by sgong-pdftron** [PDFTron/pdftron-flutter#4]
Link to the article: https://www.pdftron.com/documentation/android/guides/flutter/setup

Feedback: Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory). Suggestion: add 'tools:replace="android:appComponentFactory"' to element at AndroidManifest.xml:11:5-36:19 to override.

**Comment by Neolisour** [comment]
Does anyone solve this issue?

**Comment by sgong-pdftron** [comment]
@Neolisour could you submit a ticket at https://www.pdftron.com/form/report-bug so we can take a closer look? Thanks.

**Comment by bbozhidarov** [comment]
Has anyone solved that? I have the same issue. I put **tools:replace="android:appComponentFactory"** in the **AndroidManifest.xml** file and the **&lt;application&gt;** tag, but no luck. Then I get the following.

**D:\User\mobile\app\android\app\src\main\AndroidManifest.xml:22:5-54:19 Error: tools:replace specified at line:22 for attribute android:appComponentFactory, but no new value specified**
**D:\User\mobile\app\android\app\src\main\AndroidManifest.xml Error: Validation failed, exiting**

Any help would be much appreciated. Thanks!

**Comment by sgong-pdftron** [comment]
@bbozhidarov could you submit a ticket at https://www.pdftron.com/form/report-bug so we can take a closer look? Thanks.
