### ISSUE TITLE
Web/mobile annotations missmatch

### ISSUE THREAD

**Issue by bbozhidarov** [PDFTron/pdftron-flutter#47]
**Describe the bug**
Imported annotations mismatch for web and mobile for **.jpg** files.

**Steps to Reproduce the Problem**
1. Open a **.jpg** document in either mobile or web viewer/annotator;
2. add some annotation;
3. close the viewer/annotator;
4. open the document on both web and mobile and import the annotations;
5. the annotations mismatch.

**Expected behavior**
The annotations are supposed to be consistent on web and mobile, regardless of the file extension.

**Screenshots**
![Екранна снимка 2020-12-01 133720](https://user-images.githubusercontent.com/25959787/100737266-99bc2c80-33dc-11eb-8f95-ca71bb4e5e76.png)

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android
 - Device: Nexus 5X
 - OS: Andoid

**Additional context**
Mobile SDK version:
  resolved-ref: "120c3df3977b82258962651212a04bbde1859126"
  url: "git://github.com/PDFTron/pdftron-flutter.git"
  version: "0.0.2"

Web viewer version: 7.1.2

**Comment by sgong-pdftron** [comment]
@bbozhidarov could you please provide the exact file and the exact XFDF string so we can investigate on our end?
Thanks.

**Comment by bbozhidarov** [comment]
Yes, sure. These are not exactly the same files and annotations but the issue is the same.


```
<?xml version="1.0" encoding="UTF-8"?>
<xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve">
	<add>
		<square style="solid" width="5" color="#E44234" opacity="1" creationdate="D:20201203131708Z" flags="print" date="D:20201203131708Z" name="713b992d-caba-4d18-b094-66f66bb561cb" page="0" fringe="0,0,0,0" rect="142.784,321.476,524.145,485.671" title="" />
	</add>
	<modify />
	<delete />
	<pdf-info import-version="3" version="2" xmlns="http://www.pdftron.com/pdfinfo" />
</xfdf>
```


![6030bf1e-93a8-4f89-a1a9-754e46856901967230253](https://user-images.githubusercontent.com/25959787/101022912-b42c0c80-357a-11eb-8606-48a3d57ea0b6.jpg)

**Comment by sgong-pdftron** [comment]
@bbozhidarov This should work with the default viewer and in my testing it works fine.
May I ask if you are changing the `ViewerConfig.Builder.conversionOptions` anywhere in your code?

**Comment by sgong-pdftron** [comment]
@bbozhidarov also, on WebViewer side, do you change the `pageSize` option? If so, then the size will no longer match

**Comment by bbozhidarov** [comment]
We don't set or change these properties. Is there any workaround for that?

**Comment by sgong-pdftron** [comment]
@bbozhidarov as we are having difficulty reproducing this on our end, could you please kindly provide a sample project (for both web and android) so we could check what might be the problem? You can email us at support@pdftron.com. Thanks.

**Comment by sgong-pdftron** [comment]
@bbozhidarov I will close this ticket here now and could you please send us a support ticket instead?
For reference, the following was our test result:

![anthony 07-Dec 02_49 PM](https://user-images.githubusercontent.com/20527369/101415367-9de4c000-389c-11eb-8629-3cc8f319ec9c.png)

![shirley 07-Dec 02_55 PM](https://user-images.githubusercontent.com/20527369/101415379-a3420a80-389c-11eb-9c72-3a0a3296ffad.png)


As you can see they appear to be consistent. So at this point we are unsure what might be the problem. We'd love to sort this out with you with a support ticket. Thanks.

**Comment by bbozhidarov** [comment]
Thank you for verifying that. I'll check on a fresh project, maybe something on our side.

**Comment by sgong-pdftron** [comment]
@bbozhidarov I just wanted to follow up that were you able to sort this issue out?
Thanks.
