### ISSUE TITLE
Desktop Support (Feature Request)

### ISSUE THREAD

**Issue by okpatil4u** [PDFTron/pdftron-flutter#57]
Thanks for the amazing plugin.
Do you plan to support the desktop in upcoming releases ? Are there any technical issues preventing you from doing that ?

**Comment by Leadrive** [comment]
Yes, expect desktop support!
https://flutter.dev/desktop
flutter support windows/linux/macos desktop now.

**Comment by thijskuilman** [comment]
I was wondering the same thing. Is desktop support currently something on the roadmap?

**Comment by jitendrapurohit12** [comment]
Any update on this, as Flutter for Windows is now stable.

**Comment by sgong-pdftron** [comment]
Windows is not supported at the moment, please feel free to submit a feature request here https://www.pdftron.com/form/feature-request/, or custom engineering project here: https://www.pdftron.com/form/professional-services/
