### ISSUE TITLE
how can i remove the watermark?

### ISSUE THREAD

**Issue by mlf2020** [PDFTron/pdftron-flutter#73]
How can I remove the watermark on the doc?
```
config.annotationAuthor = 'xxx';
```
this API didn't work,is there any other way?

![Snip20210305_1](https://user-images.githubusercontent.com/12659293/110063517-458f6280-7da6-11eb-9f06-88a6ba06b103.png)

**Comment by sgong-pdftron** [comment]
@mlf2020 PDFTron is a commercial solution, once you obtain a valid license key (https://www.pdftron.com/form/contact-sales/), the watermark will be gone.

> annotationAuthor
Could you please elaborate on exactly what "does not work" means? This will write a value to the annotations themselves.

**Comment by mlf2020** [comment]
this SDK does'nt supprot iOS10?

**Comment by mlf2020** [comment]
> @mlf2020 PDFTron is a commercial solution, once you obtain a valid license key (https://www.pdftron.com/form/contact-sales/), the watermark will be gone.
> 
> > annotationAuthor
> 
> Could you please elaborate on exactly what "does not work" means? This will write a value to the annotations themselves.

I have contacted sales, but i did'nt receive the license key?

**Comment by JamesTron** [comment]
The latest release of PDFTron for iOS is 64-bit only, and all devices with a 64-bit chip can run iOS 11. 64-bit chips were introduced in 2013, and the vast majority of iOS users are running 64-bit hardware. Apple does not appear to issue security updates for iOS 10. Does your app have many users who are running 32-bit hardware? The next release will include 32-bit again (we had one other customer raise this concern), but as the number of iOS users running 32-bit hardware is very small, and that these devices are no longer supported by Apple, we don't expect demand for 32-bit software to remain much longer.
