### ISSUE TITLE
Can not add new button to top nav like IOS/Android version?

### ISSUE THREAD

**Issue by MonipichMP** [PDFTron/pdftron-flutter#75]
I want to add my custom button to the top nav bar like I ever did in iOS, but here I can't any solutions to do that even I have read all of your API documents. I hope I will get solution soon! Regards!

**Comment by sgong-pdftron** [comment]
@MonipichMP do you mind share a mock up of what you are trying to achieve so we could better assist? Thanks!

**Comment by MonipichMP** [comment]
@sgong-pdftron thanks for your response! Here it is my screenshot of app and the top right button "រក្សាទុក" is what I want to add there !

![photo_2021-03-17_08-37-10](https://user-images.githubusercontent.com/39157246/111401553-14932400-86fc-11eb-94c6-11ab1e39f068.jpg)

**Comment by sgong-pdftron** [comment]
@MonipichMP This is not currently supported in Dart API however it is possible to achieve it by forking the repo and add it natively. Would that be an option for you? Thanks.

**Comment by MonipichMP** [comment]
@sgong-pdftron It would be great if your team add it. Thanks

**Comment by sgong-pdftron** [comment]
@MonipichMP This is not a trivial item to add as it replaces the entire item set of the default and replacing with special item type, i.e. text in your example, it is very custom to your application. Even if we add the ability to customize the menu items, it will be per platform norm which will be show as icons in the toolbar. So the best way would be modifying thing directly in the native code in your application. Could you please give a try? Thanks.
