### ISSUE TITLE
I just need the code for the comments to add on pdf can anyone help please

### ISSUE THREAD

**Issue by riyapatel56** [PDFTron/pdftron-flutter#76]
**Describe the bug**

**Steps to Reproduce the Problem**

**Expected behavior**

**Screenshots**

**Platform/Device Information (please complete the following information if applicable):**
 - Platform:[e.g. iOS or Android]
 - Device: [e.g. iPhone6, Google Pixel 4]
 - OS: [e.g. iOS8.1, Android Nougat]

**Additional context**

**Comment by sgong-pdftron** [comment]
@riyapatel56 Could you please describe what you are looking for in details? With screenshot and screencast, including any relevant information that you think will help us understanding what you are looking for. Thanks. 
PS please follow the issue template and fill all the information.

**Comment by riyapatel56** [comment]
I want the code of how to add comment on pdf these part is there in the pdftron, so i need the code of that for only comments

**Comment by sgong-pdftron** [comment]
@riyapatel56 I don't understand your use case, please kindly provide more info so we can better assist. You can add any comments in the viewer out of box.
