### ISSUE TITLE
App large size when run command: flutter build apk

### ISSUE THREAD

**Issue by binhithaui** [PDFTron/pdftron-flutter#8]
After using the lib and developing the release, I found that the application capacity increased from ~ 9MB to ~ 85MB.
Is there any solution to this problem?
This is my gradle:app file:

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/screen.main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.thienvietjsc.task_management"
        minSdkVersion 21
        targetSdkVersion 28
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    configurations.all {
        resolutionStrategy.force "com.android.support:appcompat-v7:28.0.0"
        resolutionStrategy.force "com.android.support:support-v4:28.0.0"
        resolutionStrategy.force "android.arch.lifecycle:runtime:1.0.3"
    }
    signingConfigs {
        release {
            keyAlias "xxxxxx"
            keyPassword 'xxxxxxxxx'
            storeFile file('xxxxxxxx')
            storePassword 'xxxxxxxx'
        }
    }
    buildTypes {
        release {
            release {
                signingConfig signingConfigs.release

                minifyEnabled true
                useProguard true

                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }
    bundle {
        abi {
            // Different APKs are generated for devices with different CPU architectures; true by default.
            enableSplit true
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.appcompat:appcompat:1.1.0-alpha01"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}

**Comment by sgong-pdftron** [comment]
@binhithaui 

By default PDFTron includes 5 native slices. You can reduce the number of slice included as described here:
https://www.pdftron.com/documentation/android/faq/split-apk

Could you give a try? Thanks.

**Comment by binhithaui** [comment]
> https://www.pdftron.com/documentation/android/faq/full-vs-standard
Thanks. I will try with build appbundle.

**Comment by binhithaui** [comment]
I tried with build release and the results were quite good. Thanks again.
![Screen Shot 2019-08-20 at 3 48 04 PM](https://user-images.githubusercontent.com/35101462/63333397-975ace00-c363-11e9-98bb-8d430f2c8c9b.png)
