### ISSUE TITLE
iOs build failing with the latest update

### ISSUE THREAD

**Issue by sandspoof** [PDFTron/pdftron-flutter#90]
The following build failure message was given after the latest PDFtron update and I don't know where to go fix this:

Error output from Xcode build:
↳
    ** ARCHIVE FAILED **

Xcode's output:
↳
    2 warnings generated.
    /Users/builder/programs/flutter_2_0_6/.pub-cache/git/pdftron-flutter-ba2159839871ec8ecacd7f1ce732b42a7b48318d/ios/Classes/PTFlutterDocumentController.m:94:19: warning: 'isBottomToolbarEnabled' is deprecated: Deprecated in PDFTron for iOS 7.2. Use thumbnailSliderEnabled instead [-Wdeprecated-declarations]
            if ([self isBottomToolbarEnabled]) {
                      ^
    In module 'Tools' imported from /Users/builder/programs/flutter_2_0_6/.pub-cache/git/pdftron-flutter-ba2159839871ec8ecacd7f1ce732b42a7b48318d/ios/Classes/PdftronFlutterPlugin.h:3:
    /Users/builder/clone/ios/Pods/PDFNet/Tools.framework/Headers/PTDocumentBaseViewController.h:244:67: note: property 'bottomToolbarEnabled' is declared deprecated here
    @property (nonatomic, assign, getter=isBottomToolbarEnabled) BOOL bottomToolbarEnabled PT_DEPRECATED_MSG(7.2, "Use thumbnailSliderEnabled instead");
                                                                      ^
    /Users/builder/clone/ios/Pods/PDFNet/Tools.framework/Headers/PTDocumentBaseViewController.h:244:88: note: 'isBottomToolbarEnabled' has been explicitly marked deprecated here
    @property (nonatomic, assign, getter=isBottomToolbarEnabled) BOOL bottomToolbarEnabled PT_DEPRECATED_MSG(7.2, "Use thumbnailSliderEnabled instead");
                                                                                          ^
    In module 'Tools' imported from /Users/builder/programs/flutter_2_0_6/.pub-cache/git/pdftron-flutter-ba2159839871ec8ecacd7f1ce732b42a7b48318d/ios/Classes/PdftronFlutterPlugin.h:3:
    /Users/builder/clone/ios/Pods/PDFNet/Tools.framework/Headers/ToolsDefines.h:87:41: note: expanded from macro 'PT_DEPRECATED_MSG'
    #define PT_DEPRECATED_MSG(version, msg) \
                                            ^
    In module 'UIKit' imported from /Users/builder/clone/ios/Pods/Target Support Files/pdftron_flutter/pdftron_flutter-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In module 'CoreFoundation' imported from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode-12.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/AvailabilityMacros.h:184:64: note: expanded from macro '\
    DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    /Users/builder/programs/flutter_2_0_6/.pub-cache/git/pdftron-flutter-ba2159839871ec8ecacd7f1ce732b42a7b48318d/ios/Classes/PTFlutterDocumentController.m:440:10: warning: 'bottomToolbarEnabled' is deprecated: Deprecated in PDFTron for iOS 7.2. Use thumbnailSliderEnabled instead [-Wdeprecated-declarations]
        self.bottomToolbarEnabled = YES;
             ^
    In module 'Tools' imported from /Users/builder/programs/flutter_2_0_6/.pub-cache/git/pdftron-flutter-ba2159839871ec8ecacd7f1ce732b42a7b48318d/ios/Classes/PdftronFlutterPlugin.h:3:
    /Users/builder/clone/ios/Pods/PDFNet/Tools.framework/Headers/PTDocumentBaseViewController.h:244:88: note: 'bottomToolbarEnabled' has been explicitly marked deprecated here
    @property (nonatomic, assign, getter=isBottomToolbarEnabled) BOOL bottomToolbarEnabled PT_DEPRECATED_MSG(7.2, "Use thumbnailSliderEnabled instead");
                                                                                          ^
    In module 'Tools' imported from /Users/builder/programs/flutter_2_0_6/.pub-cache/git/pdftron-flutter-ba2159839871ec8ecacd7f1ce732b42a7b48318d/ios/Classes/PdftronFlutterPlugin.h:3:
    /Users/builder/clone/ios/Pods/PDFNet/Tools.framework/Headers/ToolsDefines.h:87:41: note: expanded from macro 'PT_DEPRECATED_MSG'
    #define PT_DEPRECATED_MSG(version, msg) \
                                            ^
    In module 'UIKit' imported from /Users/builder/clone/ios/Pods/Target Support Files/pdftron_flutter/pdftron_flutter-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In module 'CoreFoundation' imported from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode-12.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/AvailabilityMacros.h:184:64: note: expanded from macro '\
    DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    /Users/builder/programs/flutter_2_0_6/.pub-cache/git/pdftron-flutter-ba2159839871ec8ecacd7f1ce732b42a7b48318d/ios/Classes/PTFlutterDocumentController.m:445:10: error: 'pageFitsBetweenBars' is unavailable: This API is no longer availble.
        self.pageFitsBetweenBars = !hidesToolbarsOnTap; // Tools default is enabled.
             ^
    In module 'Tools' imported from /Users/builder/programs/flutter_2_0_6/.pub-cache/git/pdftron-flutter-ba2159839871ec8ecacd7f1ce732b42a7b48318d/ios/Classes/PdftronFlutterPlugin.h:3:
    /Users/builder/clone/ios/Pods/PDFNet/Tools.framework/Headers/PTDocumentBaseViewController.h:232:28: note: 'pageFitsBetweenBars' has been explicitly marked unavailable here
    @property (nonatomic) BOOL pageFitsBetweenBars PT_UNAVAILABLE_MSG("This API is no longer availble.");
                               ^
    2 warnings and 1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Encountered error while archiveing for device.

Build failed :|
Failed to build for iOS

**Configurations:**
Flutter: 2.0.3
XCode: 12.5

This looks to be where the problem is but I can't find where that api is being referenced in my code. Any help would be appreciated!

**Comment by JamieDass** [comment]
Hi @sandspoof,

Are you able to tell us which version of the `pdftron-flutter` wrapper you are using?
I think if you update to a more recent version then the issue should be resolved. The latest version is v0.0.45.

To update your packages you can run `flutter packages upgrade` from inside your app directory.

**Comment by sandspoof** [comment]
Hi @JamieDass 

I'm not sure what version of pdftron-flutter I'm using, but my _Podfile.lock_ says 0.0.1

![image](https://user-images.githubusercontent.com/54887123/118478246-f0f65500-b70f-11eb-8857-8d46af6e1dae.png)

I only want to update that package. How am I able to do this without updating any other packages?

Thank you for the quick response.

**Comment by JamieDass** [comment]
Hi @sandspoof,

The version number in the Podfile.lock is not accurate but is just due to the way flutter generates the file during integration.
You should be able to find the correct version number if you search for `pdftron_flutter` in the `pubspec.lock` file in your app's root directory.

To upgrade a specific package I believe you can run the following command:
`dart pub upgrade pdftron_flutter`

**Comment by sandspoof** [comment]
Hi @JamieDass 

I upgraded the pdftron_flutter version and it's currently showing version 0.0.46. I tried a build with XCode, but got an error saying _pageFitsBetweenBars is unavailable: This API is no longer available._ I see that this is being referenced in _PTFlutterDocumentController.m_ file in the pods folder.

Did my pods folder not update maybe?

**Comment by JamieDass** [comment]
Hi @sandspoof,

Ah indeed it sounds like it hasn't been updated. Are you building the project from the command line with `flutter build ios --no-codesign` or directly in Xcode?
You could try going into the ios directory in your app's project folder and running `pod install`. Does that work?

**Comment by sandspoof** [comment]
Hi @JamieDass 

I was building directly from Xcode. Running pod install from inside the iOs directory worked at updating the pods folder.

I now just have a few deprecated packages I need to resolve before trying a build again (not pdfTron related).

Thank you for the assistance @JamieDass .
