### ISSUE TITLE
Dart Null Safety Upgrade

### ISSUE THREAD

**Issue by neilchaudhuri** [PDFTron/pdftron-flutter#95]
I would like to upgrade my entire commercial Flutter app to use Dart's new null safety features, but at the moment, PDFTron is the only dependency holding me back. Is upgrading to null safety on your roadmap?

**Comment by sgong-pdftron** [comment]
@neilchaudhuri Thanks for bringing this to our radar. Do you mind submit a formal feature request ticket here: https://www.pdftron.com/form/request/. So we can move forward from there? Thanks!

**Comment by neilchaudhuri** [comment]
@sgong-pdftron  I tried to fill out the form, but the Product dropdown has no PDF Flutter entry. Which should I use? And what should I put for Version?

**Comment by sgong-pdftron** [comment]
@neilchaudhuri you can put either iOS or Android as Product, and Flutter as version
