### ISSUE TITLE
Light version of PDFtron

### ISSUE THREAD

**Issue by braysonjohn148** [PDFTron/pdftron-flutter#96]
Please create a light version of this package. My android app was 32mb now is 61mb. My iOS App was 81mb now is 106mb. There are alot of feature a light version could not use. Let the light version just preview the documents and remove the extra features.

**IT IS A FEATURE REQUEST I DONT WHY IT APPLIED A BUG LABEL ON IT**

**Comment by sgong-pdftron** [comment]
It is possible to reduce size of the application:
Android: https://www.pdftron.com/documentation/android/faq/reduce-apk-size/
iOS: https://www.pdftron.com/documentation/ios/guides/FAQ/framework-size/

Is this something you are interested in trying? @braysonjohn148
